version: "2.1"
services:      
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    depends_on:
      mssql-server:
        condition: service_healthy
    networks:
      intra:
        ipv4_address: 172.10.0.10    

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    container_name: mssql-container
    volumes:
      - ./docker/mssql/scripts:/tmp/scripts    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Petz@2020
    ports:
      - 1433:1433
    command: 
      - /tmp/scripts/launch-db.sh
    healthcheck:
      test: ["CMD", "bash",  "/tmp/scripts/select-db.sh"]
      interval: 30s
      timeout:  30s
      retries:  50
    networks:
      intra:
        ipv4_address: 172.10.0.11
        
  openjdk:
    image: openjdk:8
    container_name: openjdk
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://172.10.0.11;databaseName=Petz
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=Petz@2020
    depends_on:
      mssql-server:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./../target/:/home/
    entrypoint: ["sh", "-c", "java -jar /home/petz-code-cad*.jar"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl 
                                  --silent
                                  -i
                                  -H \"Content-Type: application/json\"
                                  -X GET 
                                  -d '[{\"plaintext\":\"teste\"}]' 
                                  \"http://172.10.0.12:8080/cad/client/\" 
                                  -L | grep 'HTTP/1.1 200' || exit 1"]

    networks:
      intra:
        ipv4_address: 172.10.0.12

  karate-server:
    image: qbarlas/karate-dsl
    container_name: karate-container
    environment:
      - IP_HOSTNAME=$IP_HOSTNAME
    volumes:
      - ./bdd/features:/src/features
      - ./bdd/karate-config.js:/src/assets/bdd/karate-config.js
      - ./bdd/reports:/src/target
    ports:
      - 15155:8080
    depends_on:
      openjdk:
        condition: service_healthy
    entrypoint: ["sh", "-c", "java -jar -Dkarate.ip=$IP_HOSTNAME /src/karate.jar features/"] 
    networks:
      intra:
        ipv4_address: 172.10.0.13
        
networks:
  intra:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24