version: "2.4"
services:    
    
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql-keystore-container
    restart: always
    volumes:
      - ./docker/mssql/scripts:/tmp/scripts    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Itau@2019
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD", "bash", "/tmp/scripts/launch-db.sh"]
      interval: 15s
      timeout:  10s
      retries:  10
    networks:
      intra:
        ipv4_address: 172.10.0.11
    
  openjdk:
    image: openjdk:8
    container_name: keystore-openjdk
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://172.10.0.11;databaseName=Stores
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=Itau@2019
    depends_on:
      mssql-server:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - $PWD/0.0.1/itau-latam-keystore-0.0.1.jar:/home/itau-latam-keystore-0.0.1.jar
    entrypoint: ["sh", "-c", "java -jar /home/itau-latam-keystore-0.0.1.jar"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl 
                                  --silent
                                  -i
                                  -H \"Content-Type: application/json\"
                                  -X POST 
                                  -d '[{\"plaintext\":\"teste\"}]' 
                                  \"http://172.10.0.12:8080/ppid/encrypt\" 
                                  -L | grep 'HTTP/1.1 200' || exit 1"]
      interval: 10s
      timeout:  5s
      retries:  2
    networks:
      intra:
        ipv4_address: 172.10.0.12
    
  karate-server:
    image: qbarlas/karate-dsl
    container_name: karate-container
    volumes:
      - $PWD/bdd/features:/src/features
      - $PWD/bdd/reports:/src/target
    ports:
      - 15155:8080
    depends_on:
      openjdk:
        condition: service_healthy
    networks:
      intra:
        ipv4_address: 172.10.0.13
      
networks:
  intra:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24