version: "2.4"
services:    
    
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql-keystore-container
    restart: always
    volumes:
      - ./docker/mssql/scripts:/tmp/scripts    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Itau@2019
    ports:
      - 1433:1433
    entrypoint: ["sh", "-c", "/tmp/scripts/launch-db.sh"]
    healthcheck:
      test: ["CMD", "bash", "/tmp/scripts/select-db.sh"]
      interval: 5s
      timeout:  30s
      retries:  10
    networks:
      intra:
        ipv4_address: 172.10.0.11
    
  openjdk:
    image: openjdk:8
    container_name: keystore-openjdk
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://172.10.0.11;databaseName=Stores
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=Itau@2019
    depends_on:
      mssql-server:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./../target/:/home/
    entrypoint: ["sh", "-c", "java -jar /home/itau-latam-ppid-encryptor*.jar"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl 
                                  --silent
                                  -i
                                  -H \"Content-Type: application/json\"
                                  -X POST 
                                  -d '[{\"plaintext\":\"teste\"}]' 
                                  \"http://172.10.0.12:8080/ppid/encrypt\" 
                                  -L | grep 'HTTP/1.1 200' || exit 1"]

    networks:
      intra:
        ipv4_address: 172.10.0.12
    
  karate-server:
    image: qbarlas/karate-dsl
    container_name: karate-container
    environment:
      - IP_HOSTNAME=$IP_HOSTNAME
    volumes:
      - ./bdd/features:/src/features
      - ./bdd/karate-config.js:/src/assets/bdd/karate-config.js
      - ./bdd/reports:/src/target
    ports:
      - 15155:8080
    depends_on:
      openjdk:
        condition: service_healthy
    entrypoint: ["sh", "-c", "java -jar -Dkarate.ip=$IP_HOSTNAME /src/karate.jar features/"] 
    networks:
      intra:
        ipv4_address: 172.10.0.13
      
networks:
  intra:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24